CREATE TABLE IF NOT EXISTS courses (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS students (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name TEXT
)